### ISSUE TITLE
when upgrading to 3.0.0.0 fails with missing reference

### ISSUE THREAD

**Issue by gatisb** [Geta/emailnotification#11]
`CS0012	The type 'MailboxAddress' is defined in an assembly that is not referenced. You must add a reference to assembly 'MimeKit, Version=2.10.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'.`

nuget dependencies are missing:
![image](https://user-images.githubusercontent.com/1835493/109165225-fc2a8c00-7783-11eb-8837-4cdc719a848c.png)

**Comment by valdisiljuconoks** [comment]
@winiarski91 was v3 released after your clean-up changes there?

**Comment by winiarski91** [comment]
I will take a look at this tomorrow.

**Comment by winiarski91** [comment]
@gatisb Now dependencies are shown. Please let me know if you have any problems with this package. 
![image](https://user-images.githubusercontent.com/9538522/109282697-2af54080-781e-11eb-8775-3064191e4df3.png)
