### ISSUE TITLE
use MailboxAddress.Parse in examples instead of new MailboxAddress

### ISSUE THREAD

**Issue by gatisb** [Geta/emailnotification#31]
use MailboxAddress.Parse in examples instead of new MailboxAddress due to:
`[Obsolete("This constructor will be going away due to it causing too much confusion. Use new MailboxAddress(string name, string address) or MailboxAddress.Parse(string) instead.")]`

**Comment by winiarski91** [comment]
@gatisb I think this is not valid anymore. new MailboxAddress(string name, string address) is used in this package now
